[[themes]]
name = "Stingray"
[themes.palette]
background         =   "#0e091d"
foreground         =   "#14b4b4"
black              =   "#0e091d"
red                =   "#e20340"
green              =   "#8d00cf"
yellow             =   "#e92000"
blue               =   "#008cff"
magenta            =   "#cc00aa"
cyan               =   "#14b470"
white              =   "#14b4b4"
bright_black       =   "#322a49"
bright_red         =   "#ff1b64"
bright_green       =   "#af18f5"
bright_yellow      =   "#f84d32"
bright_blue        =   "#00f0fa"
bright_magenta     =   "#ff66e6"
bright_cyan        =   "#00ffb2"
bright_white       =   "#00f0fa"
