[window]
padding       =   { x = 8, y = 8 }

[font]
normal       =   { family = "Cozette", style = "HiDpi"}
glyph_offset = { x = -1, y = 0}
size = 15

[colors]

[colors.primary]
background  =   "0x0e091d"
foreground  =   "0x14b4b4"

# Normal colors
[colors.normal]
black       =   "0x0e091d"
red         =   "0xe20340"
green       =   "0x8d00cf"
yellow      =   "0xe92000"
blue        =   "0x008cff"
magenta     =   "0xcc00aa"
cyan        =   "0x14b470"
white       =   "0x14b4b4"

# Bright colors
[colors.bright]
black       =  "0x322a49"
red         =  "0xff1b64"
green       =  "0xaf18f5"
yellow      =  "0xf84d32"
blue        =  "0x00f0fa"
magenta     =  "0xff66e6"
cyan        =  "0x00ffb2"
white       =  "0x00f0fa"
